### ISSUE TITLE
Project roadmap

### ISSUE THREAD

**Issue by ac-freeman** [ac-freeman/adder-codec-rs#53]
- [ ] Implement mixed-time representation
- [ ] Implement ADΔER re-coding ("transcode" an ADΔER stream again with different choices of _D_)
- [ ] Develop lossless compression techniques. Encode with [arithmetic-coding](https://github.com/danieleades/arithmetic-coding)
- [ ] Develop lossy compression techniques
- [ ] Be able to go from raw ADΔER -> lossy compressed ADΔER -> decoded stream -> display in video player
- [ ] Enable streaming with [Real-time Transport Protocol](https://github.com/webrtc-rs/webrtc/)
- [ ] Create a vision-type application which operates on ADΔER directly
- [ ] Link application with live compression for application-directed loss
- [ ] Link application with live transcode (from framed and/or DAVIS source) for application-directed loss
